version: '3.1'

services:
   db:
      image: postgres
      restart: always
      environment:
         - POSTGRES_USER=admin
         - POSTGRES_PASSWORD=123secret
         - POSTGRES_DB=delivery-db 
      volumes: 
         - pgdata:/data/postgres
      network_mode: host
volumes: 
  pgdata: 
    driver: local